### ISSUE TITLE
[FEA]: Create a REST Interface for NV-Ingest Service Using FastAPI

### ISSUE THREAD

**Issue by drobison00** [NVIDIA/nv-ingest#21]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Significant Improvement

### Please provide a clear description of problem this feature solves

Implement a new REST interface using FastAPI to enhance the NV-Ingest service. This interface will manage job submissions, including batch submissions, by generating unique IDs for jobs, proxying them to the NV-Ingest client, and allowing callers to fetch results with the job ID.

### Task Description
- [x] **REST API Development**: Develop a RESTful interface using FastAPI.
  - [x] **Endpoint `/submit_job`**: Accepts a POST request containing a JSON job description or a batch of job descriptions. The server will generate a unique ID for each job, submit it to the NV-Ingest service using the client library, and return the unique ID(s) to the requester.
    - Example request:
      ```bash
      curl -X POST http://localhost:8000/submit_job \
        -H "Content-Type: application/json" \
        -d '{"jobs": [{"job_data": "Details of the first job"}, {"job_data": "Details of the second job"}]}'
      ```
    - Example response:
      ```json
      {
        "job_ids": ["123e4567-e89b-12d3-a456-426614174000", "123e4567-e89b-12d3-a456-426614174001"]
      }
      ```
  - [x] **Endpoint `/fetch_job`**: Accepts a GET request with one or more job ID parameters. The server will query the NV-Ingest service for the job results associated with the given ID(s) and return them to the requester.
    - Example request:
      ```bash
      curl http://localhost:8000/fetch_job?job_ids=123e4567-e89b-12d3-a456-426614174000,123e4567-e89b-12d3-a456-426614174001
      ```
    - Example response:
      ```json
      {
        "results": [
          {"job_id": "123e4567-e89b-12d3-a456-426614174000", "output": "Output of the first job"},
          {"job_id": "123e4567-e89b-12d3-a456-426614174001", "output": "Output of the second job"}
        ]
      }
      ```

### Acceptance Criteria
- [x] A FastAPI server with the described endpoints implemented.
- [ ] The `/submit_job` endpoint must support individual and batch job submissions, generate a unique ID for each job, log the ID and job details, submit the job to NV-Ingest, and return the ID(s).
- [ ] The `/fetch_job` endpoint must be able to fetch and return results for completed jobs using job IDs.
- [ ] Integration tests demonstrating the API functionality with mock NV-Ingest service interactions.
- [ ] Documentation for endpoint usage and expected JSON structures for requests and responses.
- [x] Extend the client API to support interactions via REST MessageClient.
- [x] Extend the client CLI tool to include commands supporting the REST MessageClient.

### Implementation Notes
- [ ] Utilize UUIDs for job ID generation to ensure uniqueness.
- [ ] Ensure robust error handling for job submission and result fetching to handle potential failure modes in NV-Ingest service interactions.

### Additional context

```mermaid
sequenceDiagram
    participant Client
    participant REST_API as REST API /submit_job
    participant UUID_Generator as UUID Generator
    participant Message_Broker as Message Broker

    Client->>REST_API: Submit Job(s)
    REST_API->>UUID_Generator: Generate UUID(s)
    UUID_Generator-->>REST_API: Return UUID(s)
    REST_API->>Message_Broker: Forward Job(s)
    REST_API-->>Client: Return UUID(s)
```
